use chrono::DateTime;
use chrono::Utc;
use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;

/// Immutable point-in-time state of a project
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Snapshot {
    /// Unique snapshot identifier (UUIDv7 for natural time ordering)
    pub id: Uuid,
    /// Stable change identity (preserved across re-snapshots)
    pub change_id: Uuid,
    /// Preceding snapshot in the project timeline
    pub parent_snapshot_id: Option<Uuid>,
    /// Creation timestamp (UTC)
    pub created_at: DateTime<Utc>,
    /// Human-readable description or auto-save note
    pub message: String,
    /// Root canonical hash of the project directory tree (VcsTree)
    pub tree_hash: String,
    /// Author / user display name or identifier
    pub author: String,
    /// Whether this snapshot is marked as an explicit Milestone
    pub is_milestone: bool,
    /// Optional milestone tag (e.g. "v1.0-submission", "defense-slides")
    pub milestone_name: Option<String>,
    /// Mapped Git commit object ID (if exported to external Git)
    pub git_commit_oid: Option<String>,
    /// Flag indicating whether this was generated by automated continuous auto-save
    pub is_auto_save: bool,
    /// Detached ASCII-armored GPG signature over this snapshot's canonical signing payload
    /// (see `Snapshot::signing_payload`), if the author signed it at creation time.
    #[serde(default)]
    pub gpg_signature: Option<String>,
    /// The GPG key ID / fingerprint the author claims to have signed with (as reported by
    /// `gpg --detach-sign`'s own key selection, not independently verified until
    /// `ProjectVcs::verify_snapshot_signature` runs).
    #[serde(default)]
    pub gpg_key_id: Option<String>,
}

impl Snapshot {
    pub fn new(
        tree_hash: String,
        message: impl Into<String>,
        parent_snapshot_id: Option<Uuid>,
        author: impl Into<String>,
    ) -> Self {
        Self {
            id: Uuid::now_v7(),
            change_id: Uuid::now_v7(),
            parent_snapshot_id,
            created_at: Utc::now(),
            message: message.into(),
            tree_hash,
            author: author.into(),
            is_milestone: false,
            milestone_name: None,
            git_commit_oid: None,
            is_auto_save: false,
            gpg_signature: None,
            gpg_key_id: None,
        }
    }

    /// Canonical byte payload that gets GPG-signed / verified -- deliberately independent of
    /// field order or serde formatting so a signature stays valid even if the struct's JSON
    /// representation changes later.
    pub fn signing_payload(&self) -> Vec<u8> {
        format!(
            "apich-vcs-snapshot-v1\nid:{}\nchange_id:{}\nparent:{}\ntree_hash:{}\nauthor:{}\ncreated_at:{}\nmessage:{}\n",
            self.id,
            self.change_id,
            self.parent_snapshot_id.map(|p| p.to_string()).unwrap_or_default(),
            self.tree_hash,
            self.author,
            self.created_at.to_rfc3339(),
            self.message,
        )
        .into_bytes()
    }

    pub fn auto_save(
        tree_hash: String,
        parent_snapshot_id: Option<Uuid>,
        author: impl Into<String>,
    ) -> Self {
        let mut s = Self::new(
            tree_hash,
            "Auto-saved workspace state",
            parent_snapshot_id,
            author,
        );
        s.is_auto_save = true;
        s
    }

    pub fn mark_milestone(
        &mut self,
        name: impl Into<String>,
        description: impl Into<String>,
    ) {
        self.is_milestone = true;
        self.milestone_name = Some(name.into());
        let desc = description.into();
        if !desc.is_empty() {
            self.message = desc;
        }
    }
}
