#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IgnoreProfile {
    Academic,
    Python,
    R,
    Development,
    Rust,
    JavaScript,
    Java,
    CCpp,
    Editor,
}

impl IgnoreProfile {
    /// All known profiles, in the order they should be shown to a user
    pub fn all() -> &'static [IgnoreProfile] {
        &[
            IgnoreProfile::Development,
            IgnoreProfile::Rust,
            IgnoreProfile::JavaScript,
            IgnoreProfile::Python,
            IgnoreProfile::R,
            IgnoreProfile::Java,
            IgnoreProfile::CCpp,
            IgnoreProfile::Academic,
            IgnoreProfile::Editor,
        ]
    }

    /// Machine-readable id, stable across releases (used for config wiring / URLs)
    pub fn id(&self) -> &'static str {
        match self {
            IgnoreProfile::Academic => "academic",
            IgnoreProfile::Python => "python",
            IgnoreProfile::R => "r",
            IgnoreProfile::Development => "development",
            IgnoreProfile::Rust => "rust",
            IgnoreProfile::JavaScript => "javascript",
            IgnoreProfile::Java => "java",
            IgnoreProfile::CCpp => "ccpp",
            IgnoreProfile::Editor => "editor",
        }
    }

    /// Short human label for UI display
    pub fn label(&self) -> &'static str {
        match self {
            IgnoreProfile::Academic => "Academic (LaTeX/Typst)",
            IgnoreProfile::Python => "Python",
            IgnoreProfile::R => "R",
            IgnoreProfile::Development => "General dev",
            IgnoreProfile::Rust => "Rust / Cargo",
            IgnoreProfile::JavaScript => "JavaScript / Node",
            IgnoreProfile::Java => "Java / JVM",
            IgnoreProfile::CCpp => "C / C++",
            IgnoreProfile::Editor => "Editors & OS junk",
        }
    }

    /// Return the list of glob patterns associated with the profile
    pub fn patterns(&self) -> &'static [&'static str] {
        match self {
            IgnoreProfile::Academic => &[
                "*.aux",
                "*.fls",
                "*.fdb_latexmk",
                "*.synctex.gz",
                "*.bbl",
                "*.blg",
                "*.toc",
                "*.out",
                "*.log",
                "*.nav",
                "*.snm",
                "*.vrb",
                "*.typst-cache",
                ".typst-cache/**",
                // biber / biblatex
                "*.bcf",
                "*.run.xml",
                // makeindex
                "*.idx",
                "*.ilg",
                "*.ind",
                // glossaries package
                "*.acn",
                "*.acr",
                "*.alg",
                "*.glg",
                "*.glo",
                "*.gls",
                "*.glsdefs",
                "*.ist",
                // minted package (pygmentize cache)
                "_minted-*/**",
                // beamer / misc
                "*.thm",
                "*.dvi",
                "*.xdv",
            ],
            IgnoreProfile::Python => &[
                "__pycache__/**",
                "*.pyc",
                "*.pyo",
                "*.pyd",
                ".pytest_cache/**",
                "*.egg-info/**",
                ".venv/**",
                "venv/**",
                "env/**",
                ".ipynb_checkpoints/**",
                ".mypy_cache/**",
                ".ruff_cache/**",
                ".pytype/**",
                "dist/**",
                "build/**",
                ".tox/**",
                ".nox/**",
                "htmlcov/**",
                ".coverage",
                ".coverage.*",
                "*.cover",
                "pip-wheel-metadata/**",
                ".pdm-python",
                ".hypothesis/**",
            ],
            IgnoreProfile::R => &[
                ".Rhistory",
                ".RData",
                ".Ruserdata",
                ".Rproj.user/**",
                "renv/library/**",
                "renv/staging/**",
                "renv/python/**",
                "renv/sandbox/**",
                "*.Rout",
                "*.Rout.save",
                "*.Rout.fail",
                ".httr-oauth",
            ],
            IgnoreProfile::Development => &[
                "target/**",
                "node_modules/**",
                ".DS_Store",
                "Thumbs.db",
                ".apich/**",
                ".git/**",
                "*.log",
                ".env",
                ".env.local",
                "dist/**",
                "build/**",
                "out/**",
                "tmp/**",
                ".cache/**",
            ],
            IgnoreProfile::Rust => &[
                "target/**",
                "Cargo.lock.bak",
                "**/*.rs.bk",
                "*.pdb",
                ".cargo/registry/**",
                ".cargo/git/**",
            ],
            IgnoreProfile::JavaScript => &[
                "node_modules/**",
                "dist/**",
                "build/**",
                ".next/**",
                ".nuxt/**",
                ".svelte-kit/**",
                ".turbo/**",
                ".parcel-cache/**",
                ".vite/**",
                "coverage/**",
                "*.tsbuildinfo",
                "npm-debug.log*",
                "yarn-debug.log*",
                "yarn-error.log*",
                "pnpm-debug.log*",
                ".pnpm-store/**",
                ".yarn/cache/**",
                ".yarn/install-state.gz",
            ],
            IgnoreProfile::Java => &[
                "*.class",
                "target/**",
                "build/**",
                ".gradle/**",
                "*.jar",
                "*.war",
                "*.ear",
                ".mvn/wrapper/maven-wrapper.jar",
                "hs_err_pid*.log",
            ],
            IgnoreProfile::CCpp => &[
                "*.o",
                "*.obj",
                "*.a",
                "*.lib",
                "*.so",
                "*.so.*",
                "*.dylib",
                "*.dll",
                "*.exe",
                "*.out",
                "*.gch",
                "*.pch",
                "CMakeFiles/**",
                "CMakeCache.txt",
                "cmake-build-*/**",
                "compile_commands.json",
                ".ccls-cache/**",
            ],
            IgnoreProfile::Editor => &[
                ".vscode/**",
                ".idea/**",
                "*.swp",
                "*.swo",
                "*~",
                ".*.sw?",
                ".vim/**",
                "*.sublime-workspace",
                "*.sublime-project",
                ".fleet/**",
                ".zed/**",
                ".DS_Store",
                "Desktop.ini",
            ],
        }
    }
}
